$hook = @"
#!/usr/bin/env sh
# Auto-generated by scripts/install_hooks.ps1
set -e

echo "Running pre-commit safety checks..."

blocked_paths="\.env|orders\.json|trade_history\.csv|grid_bot\.db|^out/|^out_runs/"
if git diff --cached --name-only | grep -E "$blocked_paths" >/dev/null 2>&1; then
  echo "ERROR: Staged changes include blocked files (env/orders/db/output). Remove them from the commit."
  exit 1
fi

if git diff --cached | grep -iE "api[_-]?key|secret|token|kucoin" >/dev/null 2>&1; then
  echo "ERROR: Staged diff looks like it may contain secrets (api_key/secret/token/kucoin)."
  echo "Review and remove sensitive data before committing."
  exit 1
fi

exit 0
"@

Set-Content -Path ".git/hooks/pre-commit" -Value $hook -Encoding UTF8

if (Get-Command chmod -ErrorAction SilentlyContinue) {
    chmod +x .git/hooks/pre-commit 2>$null
}

Write-Host "Installed pre-commit hook to guard against committing secrets and generated files." -ForegroundColor Green
